apiVersion: apps/v1
kind: Deployment
metadata:
  name: starswap-api-deployment-aptos-testnet
  labels:
    app: starswap-api-aptos-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starswap-api-aptos-testnet
  template:
    metadata:
      labels:
        app: starswap-api-aptos-testnet
    spec:
      containers:
        - name: starswap-api-aptos-testnet
          image: ghcr.io/elements-studio/starcoin_starswap:sha-50df907
          ports:
            - containerPort: 8600
          env:
            - name: spring_profiles_active
              value: aptos-testnet
            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
              value: "true"
            - name: STARCOIN_MYSQL_URL
              value: "jdbc:mysql://starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com:3306/starswap_aptos_testnet?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
            - name: STARCOIN_MYSQL_USER
              value: "starcoin"
            - name: STARCOIN_MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-pwd
                  key: password
            - name: STARCOIN_SEEDS
              value: ""
            - name: STARCOIN_NETWORK
              value: ""
            - name: STARCOIN_JSON_RPC_URL
              value: ""
            - name: FARMING_BOOST_WHITELIST
              value: '{}'
            - name: CHAIN_NETWORK
              value: "aptos-testnet"
