apiVersion: apps/v1
kind: Deployment
metadata:
  name: starswap-api-deployment
  labels:
    app: starswap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starswap-api
  template:
    metadata:
      labels:
        app: starswap-api
    spec:
      containers:
        - name: starswap-api
          image: ghcr.io/elements-studio/starcoin_starswap:sha-99f2fd0
          ports:
            - containerPort: 8600
          env:
            - name: spring_profiles_active
              value: prod
            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
              value: "true"
            - name: STARCOIN_MYSQL_URL
              value: "jdbc:mysql://starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com:3306/starswap?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
            - name: STARCOIN_MYSQL_USER
              value: "starcoin"
            - name: STARCOIN_MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-pwd
                  key: password
            - name: STARCOIN_SEEDS
              value: "main1.seed.starcoin.org,main2.seed.starcoin.org"
            - name: STARCOIN_NETWORK
              value: "main"
            - name: STARCOIN_JSON_RPC_URL
              value: "https://main-seed.starcoin.org"
            - name: FARMING_BOOST_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: starswap-farming-boost-secrets
                  key: whitelist

