server:
  servlet:
    context-path: /barnard
    # "/${STARCOIN_NETWORK}"

spring:
  flyway:
    baselineOnMigrate: true
    # 如果指定 schema 包含了其他表但没有 flyway schema history 表的话，在执行 flyway migrate 命令之前须先执行 flyway baseline 命令。
    # 设置 spring.flyway.baseline-on-migrate 为 true 后，flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baselineVersion: 0.0.1
    cleanDisabled: true # flyway 的 clean 命令会删除指定 schema 下的所有 table，应该禁掉
    enabled: true # 启用或禁用 flyway


starcoin:
  event-filter:
    from-address: "0x8c109349c6bd91411d6bc962e080c4a3"
    add-liquidity-event-type-tag: "0x8c109349c6bd91411d6bc962e080c4a3::TokenSwap::AddLiquidityEvent"
    add-farm-event-type-tag: "0x8c109349c6bd91411d6bc962e080c4a3::TokenSwapFarm::AddFarmEvent"
    stake-event-type-tag: "0x8c109349c6bd91411d6bc962e080c4a3::TokenSwapFarm::StakeEvent"
    syrup-pool-stake-event-type-tag: "0x8c109349c6bd91411d6bc962e080c4a3::TokenSwapSyrup::StakeEvent"


starswap:
  contract-address: "0x8c109349c6bd91411d6bc962e080c4a3"
  token-price-service:
    base-url: http://k8s-default-starcoin-cbf39ae390-308376289.ap-northeast-1.elb.amazonaws.com/barnard/v1
    #https://price-api.starcoin.org/barnard/v1
  farming-boost:
    whitelist: "${FARMING_BOOST_WHITELIST}"


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO

      hibernate:
        tool:
          hbm2ddl: INFO

      starcoin:
        starswap:
          api: INFO
          subscribe:
            handler: INFO


